port: 4001
title: Typography Three & Four
email: paradia@algonquincollege.com
description: >
  This is the curriculum web site for DSN1543 Typography 3 course in the Graphic Design program at Algonquin College in Ottawa, Canada.
baseurl: ""
url: ""
twitter_username: alainparadis
github_username:  alainparadis

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

collections:
  posts:
    output: true
  type-3:
    output: true
  type-4:
    output: true
  type-trivia:
    output: true