port: 4001
title: Typography Three & Four
email: paradia@algonquincollege.com
description: >
  This is the curriculum web site for DSN1543 Typography 3 course in the Graphic Design program at Algonquin College in Ottawa, Canada.
baseurl: ""
url: /type
twitter_username: alainparadis
github_username:  alainparadis

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

collections:
  grimm-dust-cover:
    output: true
    level: 3
  grimms-pages:
    output: true
    level: 3
  newsletter:
    output: true
    level: 3
  assignment4:
    output: true
    level: 3
  some-assignment:
    output: true
    level: 4
  assignment5:
    output: true
  assignment6:
    output: true
  assignmentOne:
    output: true
  assignmentTwo:
    output: true
  assignmentThree:
    output: true
  assignmentFour:
    output: true
  assignmentFive:
    output: true
  assignmentSix:
    output: true
