port: 4001
title: Typography Three
email: paradia@algonquincollege.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the curriculum web site for DSN1543 Typography 3 course in the Graphic Design program at Algonquin College in Ottawa, Canada.
baseurl: ""
url: /type-3
twitter_username: alainparadis
github_username:  alainparadis
collections:
  micro-assignments:
    output: true
  type-facts:
    output: true
  grids:
    output: true
  hierarchy:
    output: true
  layout-for-the-screen:
    output: true
  magazine-layout:
    output: true
  web-type:
    output: true