port: 4001
title: Typography Three
email: paradia@algonquincollege.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the curriculum web site for DSN1543 Typography 3 course in the Graphic Design program at Algonquin College in Ottawa, Canada.
baseurl: ""
url: "alainparadis.github.io/"
twitter_username: alainparadis
github_username:  alainparadis
# Build settings
plugins:
  - jekyll-feed

collections:
  assignments:
      output: true
  micro-assignments:
      output: true
  type-facts:
      output: true
