port: 4001
title: Typography Three & Four
email: paradia@algonquincollege.com
description: >
  This is the curriculum web site for DSN1543 Typography 3 course in the Graphic Design program at Algonquin College in Ottawa, Canada.
baseurl: ""
url: ""
twitter_username: alainparadis
github_username:  alainparadis
plugins: [jekyll-paginate]
paginate_path: "/blog/page:num/"
paginate: 8

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

collections:
  type:
    output: true
  type-3:
    output: true
  type-4:
    output: true
  kb:
    output: true
  posts:
    output: true