port: 4001
title: Typography Three & Four
email: paradia@algonquincollege.com
description: >
  This is the curriculum web site for DSN1543 Typography 3 course in the Graphic Design program at Algonquin College in Ottawa, Canada.
baseurl: ""
url: /type
twitter_username: alainparadis
github_username:  alainparadis
collections:
  assignment1:
    output: true
  assignment2:
    output: true
  assignment3:
    output: true
  assignment4:
    output: true
  assignment5:
    output: true
  assignment6:
    output: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
